import "./globals.css";
import localFont from "next/font/local";
import SessionWrapper from "@/context/Provider";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const AdobeClean = localFont({
  src: [
    {
      path: "../fonts/AdobeClean-Bold.otf",
      weight: "700",
    },
    {
      path: "../fonts/AdobeClean-BoldSemi.otf",
      weight: "600",
    },
    {
      path: "../fonts/AdobeClean-Semi.otf",
      weight: "500",
    },
    {
      path: "../fonts/AdobeClean-Regular.otf",
      weight: "400",
    },
    {
      path: "../fonts/AdobeClean-Light.otf",
      weight: "300",
    },
  ],
});

export const metadata = {
  title: "MGI | PT Mitra Global Informatika",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("bg-white", AdobeClean.className)}>
        <SessionWrapper>
          {children}
          <Toaster position="bottom-right"/>
        </SessionWrapper>
      </body>
    </html>
  );
}
